<a href="https://colab.research.google.com/github/JazminDenisse/AI2023-2_DenisseVargas/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

#create an array with random inteher values between 1 and 10
a = np.random.randint(1, 11, size=(3,4))
b = np.random.randint(1, 11, size=(3,4))
print(a)
print(b)
print(a.shape)
print(b.shape)
print('Adding numbers')
#plus
print(a+b)
print('Substracting numbers')
#minus
print(a-b)
print('Multiplication numbers')
#times
print(a*b)

print('Add')
print(np.add(a,b))
print('Substract')
print(np.multiply(a,b))
print('Multiply')
print(np.subtract(a,b))
print('Divide')
print(np.divide(a,b))

[[ 5  6  7  6]
 [10  1  7  9]
 [ 6  4  3  3]]
[[ 9  9  5  1]
 [ 3  5  1 10]
 [ 6  8 10  4]]
(3, 4)
(3, 4)
---------------
Adding numbers
[[14 15 12  7]
 [13  6  8 19]
 [12 12 13  7]]
Substracting numbers
[[-4 -3  2  5]
 [ 7 -4  6 -1]
 [ 0 -4 -7 -1]]
Multiplication numbers
[[45 54 35  6]
 [30  5  7 90]
 [36 32 30 12]]
Add
[[14 15 12  7]
 [13  6  8 19]
 [12 12 13  7]]
Substract
[[45 54 35  6]
 [30  5  7 90]
 [36 32 30 12]]
Multiply
[[-4 -3  2  5]
 [ 7 -4  6 -1]
 [ 0 -4 -7 -1]]
Divide
[[0.55555556 0.66666667 1.4        6.        ]
 [3.33333333 0.2        7.         0.9       ]
 [1.         0.5        0.3        0.75      ]]


In [8]:
m1 = np.random.randint(1, 11, size=(3,4))
m2 = np.random.randint(1, 11, size=(4,8))
print('Matriz 1')
print(m1)
print(m1.shape)
print('Matriz 2')
print(m2)
print(m2.shape)
print('---------------------------')
print('Forma 1')
print(np.dot(m1,m2))
print('Forma 2')
print(m1.dot(m2))
print(np.dot(m1,m2).shape)

Matriz 1
[[ 5  4  7  2]
 [ 6 10  7  5]
 [ 7  1 10  9]]
(3, 4)
Matriz 2
[[ 9  2  8  6  1  4  3  7]
 [ 1  7  5  8 10  5  1  8]
 [ 9  6  5  7  5  5  1 10]
 [ 1  4  4  2  7  3  4  7]]
(4, 8)
---------------------------
Forma 1
[[114  88 103 115  94  81  34 151]
 [132 144 153 175 176 124  55 227]
 [163 117 147 138 130 110  68 220]]
Forma 2
[[114  88 103 115  94  81  34 151]
 [132 144 153 175 176 124  55 227]
 [163 117 147 138 130 110  68 220]]
(3, 8)


In [9]:
a = np.random.randint(1, 11, size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[2 1]
 [3 7]]
[[2 3]
 [1 7]]


In [16]:
#broadcast
x = np.random.randint(1, 11, size=(4,3))
y = np.array([1,0,2])

print(x.shape)
print(y.shape)

z=np.empty_like(x)
print('-----------')
print(x)
print('-----------')
print(y)
print(z.shape)
print('-----------')
print(z)

(4, 3)
(3,)
-----------
[[6 2 8]
 [3 9 1]
 [6 4 8]
 [8 7 2]]
-----------
[1 0 2]
(4, 3)
-----------
[[7 5 7]
 [4 9 5]
 [8 6 4]
 [5 5 8]]


In [17]:
for i in range(4):
  z[i,:]=x[i,:]+y
print(z)

[[ 7  2 10]
 [ 4  9  3]
 [ 7  4 10]
 [ 9  7  4]]


In [18]:
z=x+y
print(z)

[[ 7  2 10]
 [ 4  9  3]
 [ 7  4 10]
 [ 9  7  4]]


In [19]:
#para comentar varias lineas de codigo se usa triple comillas simples """ """

a=np.array([1,2,3])
print(a)
print('---------------')

b = np.full((6,3),[a])
print(b)
print('---------------')

c= np.tile(a,(6,1))
print(c)

[1 2 3]
---------------
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
---------------
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [22]:
m1 = np.random.randint(0, 10, size=(6,6))
print(m1)
aux=np.mean(m1)
print(aux)

np.mean(m1, axis=1) #promedio por filas
np.mean(m1, axis=0) #promedio por filas

print('Promedio por filas')
print(np.mean(m1, axis=1))
print('Promedio por columnas')
print(np.mean(m1, axis=0))

[[9 2 8 6 8 4]
 [7 1 0 0 4 0]
 [9 7 1 2 0 6]
 [9 3 5 5 4 8]
 [2 7 7 2 7 9]
 [9 4 4 0 4 2]]
4.583333333333333
Promedio por filas
[6.16666667 2.         4.16666667 5.66666667 5.66666667 3.83333333]
Promedio por columnas
[7.5        4.         4.16666667 2.5        4.5        4.83333333]
