<a href="https://colab.research.google.com/github/JazminDenisse/AI2023-2_DenisseVargas/blob/main/NumPy2_ExercisePractica2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

aux=np.array([1,2,4,5])
print(aux)
print(aux.shape)
print('---------')

aux=np.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))
print('-----------------------')

tmp=np.zeros((4,4))
print(tmp)
print('---------------')

tmp=np.full((4,4),5)
print(tmp)
print('-----------')

tmp=np.eye(4,4)
print(tmp)
print('---------------')

tmp=np.ones((4,4))
print(tmp)
print('---------------')

[1 2 4 5]
(4,)
---------
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
-----------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
---------------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
-----------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
---------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
---------------


**Matriz** **3x3**

In [13]:
tmp=np.random.random((3,3))
print(tmp)
print('------------------------------------')

tmp=10*np.random.random((4,4))
print(tmp)
print('-----------------------------------------------')

[[0.38397416 0.45062069 0.52480177]
 [0.52609252 0.19304163 0.4415892 ]
 [0.48146876 0.4536683  0.31365229]]
------------------------------------
[[5.48513019e-01 6.96127477e+00 6.96797756e+00 4.91572597e-01]
 [9.60710922e+00 8.54517750e+00 2.59489348e+00 2.99738255e+00]
 [6.09129656e+00 8.71124228e+00 9.01453386e+00 7.15587796e+00]
 [5.07816557e+00 2.02891221e+00 5.82154871e+00 8.39363209e-03]]
-----------------------------------------------


In [14]:
print(tmp[:2,:2])
print('-------------------------')
print(tmp[2:4,2:4])
print('-------------------------')

[[0.54851302 6.96127477]
 [9.60710922 8.5451775 ]]
-------------------------
[[9.01453386e+00 7.15587796e+00]
 [5.82154871e+00 8.39363209e-03]]
-------------------------


**Fila 0 y Fila 1**

In [15]:
print(tmp[1,1])
print('-----------------')
print(tmp[2,2])
print('-----------------')

8.545177503592999
-----------------
9.014533864072204
-----------------


**Valor del medio**

**Filtrar datos**

In [16]:
tmp=10*np.random.random((4,4))
print(tmp)

[[6.33376754 2.37262864 4.14988159 9.49185824]
 [8.1941148  0.66152382 5.66630502 0.12394806]
 [2.29515942 1.8980852  1.55144554 9.11164025]
 [8.85829257 9.93231222 6.69904084 0.26547399]]


**Filtrar datos mayor a 5**

In [17]:
mask=tmp>5
print(mask)
print('---------------------------')
print(tmp[mask])
print('----------------------------------')

[[ True False False  True]
 [ True False  True False]
 [False False False  True]
 [ True  True  True False]]
---------------------------
[6.33376754 9.49185824 8.1941148  5.66630502 9.11164025 8.85829257
 9.93231222 6.69904084]
----------------------------------


**Valores que dejen pasar de 2 a 4**

In [18]:
mask = (tmp >=2) & (tmp<=4)
print(tmp[mask])

[2.37262864 2.29515942]


**Otro ejercico de Filtro de valores enteros y aleatorerios y filtrar los numeros pares**

In [19]:
import numpy as np
integer_array =np.random.randint(0,10,(4,4))
print(integer_array)

[[8 2 8 1]
 [4 0 1 4]
 [6 0 1 8]
 [9 3 3 1]]


In [25]:
tmp = np.random.randint(0, 11, size=(4, 4))
print(tmp)
print('-------------------------------')
mask = np.mod(tmp, 2) == 0
print(tmp[mask])


[[3 8 3 2]
 [7 9 1 2]
 [6 0 5 9]
 [7 5 9 4]]
-------------------------------
[8 2 2 6 0 4]
