<a href="https://colab.research.google.com/github/JazminDenisse/AI2023-2_DenisseVargas/blob/main/NumPy1_ExercisePractica1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

aux=np.array([1,2,4,5])
print(aux)
print(aux.shape)
print('-----------------')

aux=np.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))
print('-----------------')

tmp=np.zeros((4,4))
print(tmp)
print('------------------')

tmp=np.full((4,4),5)
print(tmp)
print('------------------')

tmp=np.eye(4,4)
print(tmp)
print('------------------')

tmp=np.ones((4,4))
print(tmp)
print('------------------')

[1 2 4 5]
(4,)
-----------------
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
-----------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
------------------
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
------------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
------------------


**Matriz** **3x3**

In [ ]:
tmp=np.random.random((4,4))
print(tmp)
print('------------------------------------------------')

tmp=10*np.random.random((4,4))
print(tmp)

[[0.83963243 0.83452151 0.75856326 0.16233382]
 [0.22874657 0.57160354 0.0787817  0.43682834]
 [0.08036164 0.48661799 0.85042441 0.52715937]
 [0.15393588 0.84387395 0.38597585 0.32620923]]
------------------------------------------------
[[7.18497716 6.74996732 7.02304128 4.5380441 ]
 [3.00533412 3.69645958 4.28589187 3.22105599]
 [3.41157707 8.00830708 3.50044401 3.37442512]
 [0.30116508 1.09428786 6.30152756 3.36500116]]


In [ ]:
print(tmp[:2,:2])
print('--------------------------')
print(tmp[2:4,2:4])

[[8.03940197 2.95599936]
 [6.83848928 5.50687189]]
--------------------------
[[8.14444659]]


**Fila 0 y Fila 1**

In [ ]:
print(tmp[:2,1:3])

[[7.20109249 8.95913144]
 [0.33299879 5.76461405]]


**Valor del medio**

In [ ]:
print(tmp[2,2])
print('---------------')
print(tmp[2:4,2:4])

1.0
---------------
[[1. 1.]
 [1. 1.]]


**Filtrar datos**

In [ ]:
tmp=10*np.random.random((4,4))
print(tmp)

[[6.36167921 1.62270072 4.32455403 3.29099991]
 [3.00738219 3.30396165 1.60973216 6.15046404]
 [2.65970041 8.82095086 0.71834159 3.98576834]
 [6.07341791 6.08965991 3.94465635 6.35936522]]


**Filtrar datos mayor a 5**

In [ ]:
mask=tmp>5
print(mask)
print('------------------')
print(tmp[mask])
print('------------------')

[[ True  True  True False]
 [False False False False]
 [False  True False False]
 [False False  True False]]
------------------
[7.18497716 6.74996732 7.02304128 8.00830708 6.30152756]
------------------


**Valores que dejen pasar de 2 a 4**

In [ ]:
mask = (tmp>=2) & (tmp<=4)
print(tmp[mask])

[3.00533412 3.69645958 3.22105599 3.41157707 3.50044401 3.37442512
 3.36500116]


**Otro ejercico de Filtro de valores enteros y aleatorerios y filtrar los numeros pares**

In [ ]:
import numpy as np
integer_array =np.random.randint(0,10,(4,4))
print(integer_array)

[[2 9 6 6]
 [0 7 1 6]
 [1 5 9 0]
 [5 9 4 7]]


In [ ]:
tmp = np.random.randint(0, 11, size=(4, 4))
print(tmp)
print('------------------')
mask = np.mod(tmp, 2) == 0
print(tmp[mask])

[[ 5  5  2  0]
 [ 6  4  1  3]
 [ 3  2  6  9]
 [ 2 10  0  8]]
------------------
[ 2  0  6  4  2  6  2 10  0  8]
